import Link from 'next/link';
import { AwardIcon, BookOpenIcon, ChevronRightIcon, FileTextIcon, ShieldCheckIcon, UsersIcon } from '@/components/icons';
import { createClient } from '@/lib/supabase/server';

export default async function AdminDashboard(){
  const supabase=await createClient(); const {data:{user}}=await supabase.auth.getUser(); if(!user)throw new Error('Principal authentication required.');
  const [profileResult,profilesResult,applicationsResult,financeResult,auditResult]=await Promise.all([
    supabase.from('profiles').select('full_name').eq('id',user.id).single(),
    supabase.from('profiles').select('id,role,account_status'),
    supabase.from('applications').select('id,status,enrolled_student_id'),
    (supabase as any).from('student_finance_accounts').select('student_id,status,amount_due,amount_paid'),
    supabase.from('audit_log').select('id,actor_id,action,target_table,target_id,created_at').order('created_at',{ascending:false}).limit(6)
  ]);
  const error=profileResult.error||profilesResult.error||applicationsResult.error||financeResult.error||auditResult.error;if(error)throw new Error('Principal overview could not be loaded.');
  const profiles:any[]=profilesResult.data??[];const applications:any[]=applicationsResult.data??[];const finance:any[]=financeResult.data??[];const audits:any[]=auditResult.data??[];const name=(profileResult.data as any)?.full_name??'MIPC Principal';
  const count=(role:string)=>profiles.filter((p)=>p.role===role&&p.account_status==='active').length;const pending=applications.filter((a)=>['pending','under_review'].includes(a.status)).length;const registered=profiles.filter((p)=>p.role==='student'&&p.account_status==='active').length;const uncleared=finance.filter((a)=>!['cleared','waived'].includes(a.status)).length;
  return <div className="space-y-8"><section className="rounded-2xl bg-gradient-to-r from-mipc-navy-950 to-mipc-green-900 p-6 text-white shadow-academic sm:p-8"><p className="text-xs font-bold uppercase tracking-[.18em] text-mipc-green-200">Office of the Principal</p><h1 className="mt-2 font-display text-3xl font-bold">Institutional oversight · {name}</h1><p className="mt-3 max-w-3xl text-sm leading-6 text-white/70">Oversee academic departments, student registration, finance, staff access and the institutional audit trail. Operational responsibility remains delegated to HOD, Registrar and Finance roles.</p></section>
    <div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4"><Metric label="Registered students" value={registered}/><Metric label="Active HODs" value={count('hod')}/><Metric label="Active lecturers" value={count('lecturer')}/><Metric label="Finance not cleared" value={uncleared}/></div>
    <div className="grid gap-5 lg:grid-cols-3"><GovernanceCard href="/hod" title="Academic departments" body="Oversee HOD control of lecturers, classes and course teaching assignments." icon={<BookOpenIcon className="h-6 w-6"/>}/><GovernanceCard href="/registrar" title="Registrar" body={`${pending} application(s) awaiting registration action. Review the official student registration process.`} icon={<AwardIcon className="h-6 w-6"/>}/><GovernanceCard href="/finance" title="Finance" body="Review assessment, payments, balances and student financial clearance across the college." icon={<FileTextIcon className="h-6 w-6"/>}/></div>
    <div className="grid gap-5 lg:grid-cols-2"><GovernanceCard href="/admin/users" title="Staff & user governance" body={`Provision Lecturer, HOD, Registrar and Finance identities. Active Registrar: ${count('registrar')} · Finance: ${count('finance')}.`} icon={<UsersIcon className="h-6 w-6"/>}/><GovernanceCard href="/admin/audit" title="Security & audit" body="Inspect the immutable institutional activity trail for governance and academic actions." icon={<ShieldCheckIcon className="h-6 w-6"/>}/></div>
    <section className="mipc-panel overflow-hidden"><div className="border-b border-parchment-200 p-5"><h2 className="font-display text-xl font-bold text-ink-950">Recent institutional activity</h2></div><div className="divide-y divide-parchment-200">{audits.map((log)=><div key={log.id} className="flex flex-col gap-1 p-4 sm:flex-row sm:items-center sm:justify-between"><div><p className="text-sm font-bold text-ink-950">{log.action}</p><p className="text-xs text-ink-600">{log.target_table} · {String(log.target_id).slice(-8)}</p></div><p className="text-xs font-mono text-ink-500">{new Date(log.created_at).toLocaleString('en-GB')}</p></div>)}</div></section>
  </div>;
}
function Metric({label,value}:{label:string;value:number}){return <div className="mipc-panel p-5"><p className="text-3xl font-bold text-ink-950">{value}</p><p className="mt-1 text-xs font-bold uppercase tracking-wider text-ink-600">{label}</p></div>}
function GovernanceCard({href,title,body,icon}:{href:string;title:string;body:string;icon:React.ReactNode}){return <Link href={href} className="mipc-panel group p-6"><span className="inline-flex rounded-xl bg-mipc-green-100 p-3 text-mipc-green-800">{icon}</span><h2 className="mt-4 font-display text-xl font-bold text-ink-950">{title}</h2><p className="mt-2 text-sm leading-6 text-ink-600">{body}</p><span className="mt-4 inline-flex items-center gap-1 text-sm font-bold text-mipc-green-700">Open oversight <ChevronRightIcon className="h-4 w-4"/></span></Link>}
