import assert from 'node:assert/strict';
import { readFile } from 'node:fs/promises';
import { join } from 'node:path';
import test from 'node:test';

const root = process.cwd();
const sendLinkSource = await readFile(join(root, 'src/app/api/auth/send-link/route.ts'), 'utf8');
const mailSource = await readFile(join(root, 'src/lib/portal-auth-mail.ts'), 'utf8');
const confirmPageSource = await readFile(join(root, 'src/app/auth/confirm/page.tsx'), 'utf8');
const confirmActionSource = await readFile(join(root, 'src/app/auth/confirm/actions.ts'), 'utf8');
const loginSource = await readFile(join(root, 'src/app/login/portal-link-login.tsx'), 'utf8');

test('portal sign-in tokens are generated by Supabase and delivered through MIPC SMTP', () => {
  assert.match(sendLinkSource, /admin\.auth\.admin\.generateLink\(/);
  assert.match(sendLinkSource, /type: 'magiclink'/);
  assert.match(sendLinkSource, /properties\?\.hashed_token/);
  assert.match(sendLinkSource, /sendPortalSignInEmail/);
  assert.doesNotMatch(sendLinkSource, /signInWithOtp\(/);
  assert.match(mailSource, /MIPC_SMTP_USER/);
  assert.match(mailSource, /MIPC_SMTP_PASS/);
});

test('new portal links target the dedicated scanner-safe confirmation route', () => {
  assert.match(sendLinkSource, /new URL\('\/auth\/confirm', baseUrl\)/);
  assert.match(sendLinkSource, /searchParams\.set\('token_hash', tokenHash\)/);
  assert.match(sendLinkSource, /searchParams\.set\('type', 'email'\)/);
});

test('confirmation GET is scanner-safe and requires an explicit user action', () => {
  assert.match(confirmPageSource, /form action=\{confirmEmailLink\}/);
  assert.match(confirmPageSource, /Continue to MIPC/);
  assert.doesNotMatch(confirmPageSource, /verifyOtp\(/);
});

test('confirmation action verifies token hash server-side and routes from stored profile', () => {
  assert.match(confirmActionSource, /supabase\.auth\.verifyOtp\(/);
  assert.match(confirmActionSource, /token_hash: tokenHash/);
  assert.match(confirmActionSource, /type: 'email'/);
  assert.match(confirmActionSource, /select\('role, account_status'\)/);
  assert.match(confirmActionSource, /profilePortalDestination/);
});

test('expired or consumed links produce a clear recovery message', () => {
  assert.match(loginSource, /email_link_expired/);
  assert.match(loginSource, /expired or was already consumed/);
  assert.match(loginSource, /use the newest message/);
});
