import { FileTextIcon, UsersIcon } from '@/components/icons';
import { requireActiveGovernanceRole } from '@/lib/governance-server';
import { recordStudentPayment, updateFinanceAccount } from './actions';

function money(value:number){return new Intl.NumberFormat('en-RW',{maximumFractionDigits:0}).format(value||0)}
export default async function FinanceWorkspace(){
  const { admin }=await requireActiveGovernanceRole(['finance','admin']);
  const [studentsResult,accountsResult,paymentsResult,departmentsResult,cohortsResult]=await Promise.all([
    admin.from('profiles').select('id,full_name,email,registration_number,department_id,cohort_id,registration_status').eq('role','student').order('full_name'),
    admin.from('student_finance_accounts').select('*'),
    admin.from('student_payments').select('id,student_id,amount,reference,payment_method,paid_at').order('paid_at',{ascending:false}).limit(100),
    admin.from('departments').select('id,name'),
    admin.from('cohorts').select('id,name')
  ]);
  const error=studentsResult.error||accountsResult.error||paymentsResult.error||departmentsResult.error||cohortsResult.error; if(error)throw new Error('Student finance data could not be loaded.');
  const students:any[]=studentsResult.data??[]; const accounts:any[]=accountsResult.data??[]; const payments:any[]=paymentsResult.data??[]; const departments:any[]=departmentsResult.data??[]; const cohorts:any[]=cohortsResult.data??[];
  const totalDue=accounts.reduce((sum,a)=>sum+Number(a.amount_due||0),0); const totalPaid=accounts.reduce((sum,a)=>sum+Number(a.amount_paid||0),0); const cleared=accounts.filter((a)=>['cleared','waived'].includes(a.status)).length;
  return <div className="space-y-8"><header><p className="mipc-eyebrow">Finance office</p><h1 className="mipc-page-title">Student financial clearance</h1><p className="mt-2 max-w-3xl text-sm text-ink-700">Assess each student's payable amount, record payments and set the official financial standing. Finance cannot change registration, department or class placement.</p></header>
    <div className="grid gap-4 sm:grid-cols-3"><Metric label="Assessed" value={`${money(totalDue)} RWF`} icon={<FileTextIcon className="h-5 w-5"/>}/><Metric label="Recorded paid" value={`${money(totalPaid)} RWF`} icon={<FileTextIcon className="h-5 w-5"/>}/><Metric label="Cleared / waived" value={String(cleared)} icon={<UsersIcon className="h-5 w-5"/>}/></div>
    <div className="grid gap-4">{students.map((student)=>{const account=accounts.find((a)=>a.student_id===student.id); const due=Number(account?.amount_due||0); const paid=Number(account?.amount_paid||0); const balance=Math.max(0,due-paid); const department=departments.find((d)=>d.id===student.department_id); const cohort=cohorts.find((c)=>c.id===student.cohort_id); const recent=payments.filter((p)=>p.student_id===student.id).slice(0,3); return <details key={student.id} className="mipc-panel overflow-hidden"><summary className="cursor-pointer list-none p-5 marker:content-none"><div className="flex flex-col gap-3 sm:flex-row sm:items-center sm:justify-between"><div><div className="flex flex-wrap items-center gap-2"><h2 className="font-display text-xl font-bold text-ink-950">{student.full_name}</h2><span className="mipc-status">{account?.status??'unassessed'}</span></div><p className="mt-1 text-xs font-mono font-bold text-mipc-green-700">{student.registration_number}</p><p className="mt-1 text-sm text-ink-600">{department?.name??'No department'} · {cohort?.name??'No class'}</p></div><div className="grid grid-cols-3 gap-4 text-right text-xs"><div><p className="text-ink-500">Due</p><p className="font-bold text-ink-950">{money(due)}</p></div><div><p className="text-ink-500">Paid</p><p className="font-bold text-mipc-green-700">{money(paid)}</p></div><div><p className="text-ink-500">Balance</p><p className="font-bold text-ink-950">{money(balance)}</p></div></div></div></summary>
      <div className="grid gap-6 border-t border-parchment-200 bg-[#f8faf8] p-5 xl:grid-cols-2"><form action={updateFinanceAccount} className="grid gap-4 sm:grid-cols-2"><input type="hidden" name="student_id" value={student.id}/><div><label className="mipc-label">Assessed amount (RWF)</label><input className="mipc-field" name="amount_due" type="number" min="0" step="1" defaultValue={due} required/></div><div><label className="mipc-label">Financial standing</label><select className="mipc-field" name="financial_status" defaultValue={account?.status??'unassessed'}><option value="unassessed">Unassessed</option><option value="pending">Pending</option><option value="partial">Partial</option><option value="cleared">Cleared</option><option value="overdue">Overdue</option><option value="waived">Waived</option></select></div><div className="sm:col-span-2"><label className="mipc-label">Finance notes</label><textarea className="mipc-field min-h-20" name="notes" defaultValue={account?.notes??''} maxLength={2000}/></div><div className="sm:col-span-2"><button className="mipc-button-secondary w-full" type="submit">Update financial standing</button></div></form>
      <div><form action={recordStudentPayment} className="grid gap-4 sm:grid-cols-2"><input type="hidden" name="student_id" value={student.id}/><div><label className="mipc-label">Payment amount (RWF)</label><input className="mipc-field" name="amount" type="number" min="1" step="1" required/></div><div><label className="mipc-label">Reference / receipt</label><input className="mipc-field" name="reference" maxLength={160}/></div><div><label className="mipc-label">Payment method</label><select className="mipc-field" name="payment_method" defaultValue="mobile_money"><option value="mobile_money">Mobile Money</option><option value="bank_transfer">Bank transfer</option><option value="cash">Cash</option><option value="card">Card</option><option value="scholarship">Scholarship</option><option value="other">Other</option></select></div><div><label className="mipc-label">Payment date</label><input className="mipc-field" name="paid_at" type="datetime-local"/></div><div className="sm:col-span-2"><button className="mipc-button-primary w-full !bg-mipc-green-700" type="submit">Record payment</button></div></form>{recent.length>0&&<div className="mt-5"><p className="mipc-label">Recent payments</p><div className="space-y-2">{recent.map((p)=><div key={p.id} className="flex justify-between rounded-lg bg-white p-3 text-xs"><span>{new Date(p.paid_at).toLocaleDateString('en-GB')} · {p.payment_method}</span><strong>{money(Number(p.amount))} RWF</strong></div>)}</div></div>}</div></div>
    </details>})}{students.length===0&&<div className="mipc-panel p-10 text-center text-sm text-ink-600">No student accounts are available for financial processing.</div>}</div></div>;
}
function Metric({label,value,icon}:{label:string;value:string;icon:React.ReactNode}){return <div className="mipc-panel flex items-center gap-4 p-5"><span className="rounded-xl bg-mipc-green-100 p-3 text-mipc-green-800">{icon}</span><div><p className="text-2xl font-bold text-ink-950">{value}</p><p className="text-xs uppercase tracking-wider text-ink-600">{label}</p></div></div>}
