import { BookOpenIcon, ShieldCheckIcon, UsersIcon } from '@/components/icons';
import { requireActiveGovernanceRole } from '@/lib/governance-server';
import { assignCourseLecturer, assignLecturerDepartment, assignStudentClass, setLecturerStatus } from './actions';

export default async function HodWorkspace() {
  const { profile, admin } = await requireActiveGovernanceRole(['hod', 'admin']);
  const isPrincipal = profile.role === 'admin';
  const [departmentResult, lecturerResult, studentResult, cohortResult, courseResult] = await Promise.all([
    admin.from('departments').select('id,name,code').order('name'),
    admin.from('profiles').select('id,full_name,email,department_id,account_status').eq('role','lecturer').order('full_name'),
    admin.from('profiles').select('id,full_name,email,registration_number,department_id,cohort_id,registration_status').eq('role','student').eq('registration_status','registered').order('full_name'),
    admin.from('cohorts').select('id,name,department_id,start_date').order('start_date',{ascending:false}),
    admin.from('courses').select('id,code,title,department_id,cohort_id,lecturer_id').order('code')
  ]);
  const error = departmentResult.error || lecturerResult.error || studentResult.error || cohortResult.error || courseResult.error;
  if (error) throw new Error('Department governance data could not be loaded.');
  const departments:any[] = departmentResult.data ?? [];
  const allowedDepartmentIds = isPrincipal ? departments.map((d)=>d.id) : [profile.department_id].filter(Boolean);
  const lecturers:any[] = (lecturerResult.data ?? []).filter((item:any)=> isPrincipal || item.department_id === null || allowedDepartmentIds.includes(item.department_id));
  const students:any[] = (studentResult.data ?? []).filter((item:any)=>allowedDepartmentIds.includes(item.department_id));
  const cohorts:any[] = (cohortResult.data ?? []).filter((item:any)=>allowedDepartmentIds.includes(item.department_id));
  const courses:any[] = (courseResult.data ?? []).filter((item:any)=>allowedDepartmentIds.includes(item.department_id));
  const visibleDepartments = departments.filter((d)=>allowedDepartmentIds.includes(d.id));

  return <div className="space-y-8">
    <header><p className="mipc-eyebrow">Academic department governance</p><h1 className="mipc-page-title">{isPrincipal ? 'Department oversight' : 'HOD workspace'}</h1><p className="mt-2 max-w-3xl text-sm text-ink-700">Govern lecturers in the department, place registered students into classes, and assign teaching responsibility for each course. Registration remains owned by the Registrar.</p></header>
    <div className="grid gap-4 sm:grid-cols-3"><Metric label="Lecturers" value={lecturers.length} icon={<UsersIcon className="h-5 w-5"/>}/><Metric label="Registered students" value={students.length} icon={<ShieldCheckIcon className="h-5 w-5"/>}/><Metric label="Courses" value={courses.length} icon={<BookOpenIcon className="h-5 w-5"/>}/></div>

    <section className="mipc-panel overflow-hidden"><div className="border-b border-parchment-200 p-5"><h2 className="font-display text-xl font-bold text-ink-950">Lecturer governance</h2><p className="mt-1 text-sm text-ink-600">Assign lecturers to departments and manage their active teaching access.</p></div><div className="divide-y divide-parchment-200">{lecturers.map((lecturer)=>{
      const department=departments.find((d)=>d.id===lecturer.department_id);
      return <div key={lecturer.id} className="grid gap-4 p-5 lg:grid-cols-[1.2fr_1fr_1fr] lg:items-end"><div><p className="font-semibold text-ink-950">{lecturer.full_name}</p><p className="text-xs text-ink-600">{lecturer.email}</p><p className="mt-1 text-xs font-bold text-mipc-green-700">{department?.name ?? 'Department not assigned'} · {lecturer.account_status}</p></div><form action={assignLecturerDepartment} className="flex items-end gap-2"><input type="hidden" name="lecturer_id" value={lecturer.id}/><div className="min-w-0 flex-1"><label className="mipc-label">Department</label><select name="department_id" className="mipc-field" defaultValue={lecturer.department_id ?? visibleDepartments[0]?.id ?? ''} required>{visibleDepartments.map((d)=><option key={d.id} value={d.id}>{d.name}</option>)}</select></div><button className="mipc-button-secondary" type="submit">Assign</button></form><form action={setLecturerStatus} className="flex items-end gap-2"><input type="hidden" name="lecturer_id" value={lecturer.id}/><div className="flex-1"><label className="mipc-label">Portal status</label><select name="account_status" className="mipc-field" defaultValue={lecturer.account_status}><option value="active">Active</option><option value="suspended">Suspended</option></select></div><button className="mipc-button-secondary" type="submit">Save</button></form></div>})}{lecturers.length===0&&<p className="p-8 text-center text-sm text-ink-600">No lecturer accounts are available yet. The Principal can create them from Staff & User Directory.</p>}</div></section>

    <section className="mipc-panel overflow-hidden"><div className="border-b border-parchment-200 p-5"><h2 className="font-display text-xl font-bold text-ink-950">Assign registered students to classes</h2><p className="mt-1 text-sm text-ink-600">Only students marked Registered by the Registrar appear here. Class placement automatically reconciles their cohort-managed course enrollments.</p></div><div className="divide-y divide-parchment-200">{students.map((student)=>{const department=departments.find((d)=>d.id===student.department_id); const classOptions=cohorts.filter((c)=>c.department_id===student.department_id); return <form action={assignStudentClass} key={student.id} className="grid gap-4 p-5 lg:grid-cols-[1.3fr_1fr_auto] lg:items-end"><input type="hidden" name="student_id" value={student.id}/><div><p className="font-semibold text-ink-950">{student.full_name}</p><p className="text-xs text-ink-600">{student.registration_number} · {department?.name}</p></div><div><label className="mipc-label">Class / cohort</label><select name="cohort_id" className="mipc-field" defaultValue={student.cohort_id ?? ''} required><option value="" disabled>Select class</option>{classOptions.map((c)=><option key={c.id} value={c.id}>{c.name}</option>)}</select></div><button className="mipc-button-primary !bg-mipc-green-700" type="submit">Assign class</button></form>})}{students.length===0&&<p className="p-8 text-center text-sm text-ink-600">No registered students are awaiting department placement.</p>}</div></section>

    <section className="mipc-panel overflow-hidden"><div className="border-b border-parchment-200 p-5"><h2 className="font-display text-xl font-bold text-ink-950">Assign lecturers to courses / lessons</h2><p className="mt-1 text-sm text-ink-600">A lecturer can be assigned only to a course in the same department.</p></div><div className="divide-y divide-parchment-200">{courses.map((course)=>{const department=departments.find((d)=>d.id===course.department_id); const available=lecturers.filter((l)=>l.department_id===course.department_id&&l.account_status==='active'); const current=lecturers.find((l)=>l.id===course.lecturer_id); return <form action={assignCourseLecturer} key={course.id} className="grid gap-4 p-5 lg:grid-cols-[1.3fr_1fr_auto] lg:items-end"><input type="hidden" name="course_id" value={course.id}/><div><p className="font-mono text-xs font-bold text-mipc-green-700">{course.code}</p><p className="font-semibold text-ink-950">{course.title}</p><p className="text-xs text-ink-600">{department?.name} · {current ? `Currently ${current.full_name}` : 'Unassigned'}</p></div><div><label className="mipc-label">Responsible lecturer</label><select name="lecturer_id" className="mipc-field" defaultValue={course.lecturer_id ?? ''} required><option value="" disabled>Select lecturer</option>{available.map((l)=><option key={l.id} value={l.id}>{l.full_name}</option>)}</select></div><button className="mipc-button-primary !bg-mipc-green-700" type="submit">Assign lecturer</button></form>})}{courses.length===0&&<p className="p-8 text-center text-sm text-ink-600">No courses are configured for the visible departments.</p>}</div></section>
  </div>;
}

function Metric({label,value,icon}:{label:string;value:number;icon:React.ReactNode}) { return <div className="mipc-panel flex items-center gap-4 p-5"><span className="rounded-xl bg-mipc-green-100 p-3 text-mipc-green-800">{icon}</span><div><p className="text-2xl font-bold text-ink-950">{value}</p><p className="text-xs uppercase tracking-wider text-ink-600">{label}</p></div></div>; }
