import { createClient } from '@/lib/supabase/server';

function money(value:number){return new Intl.NumberFormat('en-RW',{maximumFractionDigits:0}).format(value||0)}
export default async function StudentFinancePage(){
  const supabase=await createClient(); const {data:{user}}=await supabase.auth.getUser(); if(!user)throw new Error('Student authentication required.');
  const [accountResult,paymentsResult]=await Promise.all([
    (supabase as any).from('student_finance_accounts').select('amount_due,amount_paid,status,notes,updated_at').eq('student_id',user.id).maybeSingle(),
    (supabase as any).from('student_payments').select('id,amount,reference,payment_method,paid_at').eq('student_id',user.id).order('paid_at',{ascending:false})
  ]);
  if(accountResult.error||paymentsResult.error)throw new Error('Your finance record could not be loaded.');
  const account:any=accountResult.data; const payments:any[]=paymentsResult.data??[]; const due=Number(account?.amount_due||0); const paid=Number(account?.amount_paid||0); const balance=Math.max(0,due-paid);
  return <div className="space-y-7"><header><p className="mipc-eyebrow">Student finance</p><h1 className="mipc-page-title">My financial standing</h1><p className="mt-2 max-w-2xl text-sm text-ink-700">View the official balance and payment records entered by the MIPC Finance Office.</p></header><div className="grid gap-4 sm:grid-cols-4"><Metric label="Status" value={account?.status??'Unassessed'}/><Metric label="Assessed" value={`${money(due)} RWF`}/><Metric label="Paid" value={`${money(paid)} RWF`}/><Metric label="Balance" value={`${money(balance)} RWF`}/></div>{account?.notes&&<div className="mipc-panel p-5"><p className="mipc-label">Finance note</p><p className="mt-2 text-sm leading-6 text-ink-700">{account.notes}</p></div>}<section className="mipc-panel overflow-hidden"><div className="border-b border-parchment-200 p-5"><h2 className="font-display text-xl font-bold text-ink-950">Payment history</h2></div><div className="overflow-x-auto"><table className="w-full min-w-[620px] text-left text-sm"><thead className="bg-parchment-50 text-xs uppercase tracking-wider text-ink-600"><tr><th className="px-5 py-3">Date</th><th className="px-5 py-3">Method</th><th className="px-5 py-3">Reference</th><th className="px-5 py-3 text-right">Amount</th></tr></thead><tbody className="divide-y divide-parchment-200">{payments.map((p)=><tr key={p.id}><td className="px-5 py-4">{new Date(p.paid_at).toLocaleDateString('en-GB')}</td><td className="px-5 py-4 capitalize">{String(p.payment_method).replaceAll('_',' ')}</td><td className="px-5 py-4 font-mono text-xs">{p.reference??'—'}</td><td className="px-5 py-4 text-right font-bold">{money(Number(p.amount))} RWF</td></tr>)}</tbody></table></div>{payments.length===0&&<p className="p-8 text-center text-sm text-ink-600">No payments have been recorded yet.</p>}</section></div>;
}
function Metric({label,value}:{label:string;value:string}){return <div className="mipc-panel p-5"><p className="text-xl font-bold capitalize text-ink-950">{value}</p><p className="mt-1 text-xs uppercase tracking-wider text-ink-600">{label}</p></div>}
