import { ShieldCheckIcon } from '@/components/icons';
import { requireActiveGovernanceRole } from '@/lib/governance-server';
import { updateStudentRegistration } from '../actions';

export default async function RegistrarStudents() {
  const { admin } = await requireActiveGovernanceRole(['registrar','admin']);
  const [studentsResult, departmentsResult, cohortsResult] = await Promise.all([
    admin.from('profiles').select('id,full_name,email,registration_number,department_id,cohort_id,year_of_study,registration_status,account_status').eq('role','student').order('full_name'),
    admin.from('departments').select('id,name,code').order('name'),
    admin.from('cohorts').select('id,name,department_id').order('name')
  ]);
  if(studentsResult.error||departmentsResult.error||cohortsResult.error) throw new Error('Student register could not be loaded.');
  const students:any[]=studentsResult.data??[]; const departments:any[]=departmentsResult.data??[]; const cohorts:any[]=cohortsResult.data??[];
  return <div className="space-y-7"><header><p className="mipc-eyebrow">Registrar · authoritative student register</p><h1 className="mipc-page-title">Registered students</h1><p className="mt-2 max-w-3xl text-sm text-ink-700">Maintain registration identity and standing. Department class placement is shown for reference but remains governed by the HOD.</p></header>
    <div className="grid gap-4">{students.map((student)=>{const department=departments.find((d)=>d.id===student.department_id); const cohort=cohorts.find((c)=>c.id===student.cohort_id); return <details key={student.id} className="mipc-panel overflow-hidden"><summary className="cursor-pointer list-none p-5 marker:content-none"><div className="flex flex-col gap-3 sm:flex-row sm:items-center sm:justify-between"><div><div className="flex flex-wrap items-center gap-2"><h2 className="font-display text-xl font-bold text-ink-950">{student.full_name}</h2><span className="mipc-status">{student.registration_status??'registered'}</span></div><p className="mt-1 font-mono text-xs font-bold text-mipc-green-700">{student.registration_number}</p><p className="mt-1 text-sm text-ink-600">{department?.name??'No department'} · {student.year_of_study?`Year ${student.year_of_study}`:'Year not assigned'}</p></div><div className="text-sm text-ink-600"><p>{student.email}</p><p className="mt-1 text-xs font-bold">Class: {cohort?.name??'Awaiting HOD assignment'}</p></div></div></summary>
      <form action={updateStudentRegistration} className="grid gap-4 border-t border-parchment-200 bg-[#f8faf8] p-5 sm:grid-cols-2 lg:grid-cols-4"><input type="hidden" name="student_id" value={student.id}/><div className="lg:col-span-2"><label className="mipc-label">Full legal name</label><input name="full_name" className="mipc-field" defaultValue={student.full_name} required/></div><div><label className="mipc-label">Registration number</label><input name="registration_number" className="mipc-field uppercase" defaultValue={student.registration_number??''} required/></div><div><label className="mipc-label">Email</label><input name="email" type="email" className="mipc-field" defaultValue={student.email} required/></div><div><label className="mipc-label">Department</label><select name="department_id" className="mipc-field" defaultValue={student.department_id??''} required>{departments.map((d)=><option key={d.id} value={d.id}>{d.name}</option>)}</select></div><div><label className="mipc-label">Year of study</label><select name="year_of_study" className="mipc-field" defaultValue={student.year_of_study?String(student.year_of_study):''}><option value="">Not assigned</option>{[1,2,3,4,5,6,7,8].map((y)=><option key={y} value={y}>Year {y}</option>)}</select></div><div><label className="mipc-label">Registration standing</label><select name="registration_status" className="mipc-field" defaultValue={student.registration_status??'registered'}><option value="provisional">Provisional</option><option value="registered">Registered</option><option value="deferred">Deferred</option><option value="withdrawn">Withdrawn</option><option value="graduated">Graduated</option></select></div><div><label className="mipc-label">HOD class placement</label><div className="mipc-field flex items-center text-ink-600">{cohort?.name??'Not assigned'}</div></div><div className="sm:col-span-2 lg:col-span-4 flex justify-end"><button className="mipc-button-primary !bg-mipc-green-700" type="submit"><ShieldCheckIcon className="h-4 w-4"/> Save registration</button></div></form>
    </details>})}{students.length===0&&<div className="mipc-panel p-10 text-center text-sm text-ink-600">No student registrations are recorded yet.</div>}</div></div>;
}
